language: python
sudo: false

python:
    - "2.7"

addons:
  apt:
    packages:
    - python-nose
    - python-scipy
    - python-matplotlib

env:
    - PYTHON=2.7 TEST=standard
    - PYTHON=3.4 TEST=standard
    - PYTHON=3.4 TEST=extra

virtualenv:
    system_site_packages: true

before_install:
    - travis_retry pip install -r requirements.txt;

install:
    - if [ "${TEST}" != "extra" ]; then
        python setup.py install;
      fi;

script:
    - if [ "${TEST}" == "extra" ]; then
        make flake;
      else
        nosetests --with-timer --timer-top-n=5;
      fi;

after_success:
    # Need to run from source dir to execute appropriate "git" commands
    coveralls
