# MMPA mmpa analyses
#
# Public.

FROM ubuntu:trusty

MAINTAINER Jasper J.F. van den Bosch, japsai@gmail.com

RUN apt-get update && apt-get install -y \
    default-jre \
    build-essential \
    git-core \
    libpng-dev \
    libxml2-dev \
    libxslt1-dev\
    python-setuptools \
    python-pip \
    python-numpy \
    python-scipy \
    python-matplotlib \
    python-sklearn \
    ipython
RUN sudo pip install nibabel


