# MNE meg analysis
#
# Public.

FROM ubuntu:trusty

MAINTAINER Jasper J.F. van den Bosch, japsai@gmail.com

RUN apt-get update 
RUN apt-get install -y \
    default-jre \
    build-essential \
    git-core \
    cmake \
    bzip2 \
    liblzo2-2 \
    liblzo2-dev \
    zlib1g \
    zlib1g-dev \
    libfreetype6-dev \
    libpng-dev \
    libxml2-dev \
    libxslt1-dev\
    cython \
    python-nose \
    python-coverage \
    python-setuptools \
    python-pip \
    python-numpy \
    python-numexpr \
    python-tables \
    python-tables-lib \
    python-scipy \
    python-matplotlib \
    python-pandas \
    python-pandas-lib \
    python-sklearn \
    python-cairosvg \
    python-cssselect \
    python-joblib \
    python-pyglet \
    python-patsy \
    python-statsmodels \
    python-statsmodels-lib \
    ipython
RUN pip install mne





